baseURL = "https://vvvv.org/"
languageCode = "en-us"
pagination.pagerSize = 20
pagination.path = "page"
summaryLength = 20
title = "vvvv - visual live-programming for .NET"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = -1 # priority omitted from rendered sitemap

[Services.RSS]
  limit = 10

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
	Access-Control-Allow-Origin = '*'

[markup]
	[markup.goldmark.renderer]
	      hardWraps = false
	      unsafe = true
	      xhtml = false

# Change the default theme to be use when building the site with Hugo
theme = "hugo-creative-theme-master"

[taxonomies]
category = 'categories'
tag = 'tags'
author = 'author'

[permalinks]
#blog-archive = '/archive/:sections[1]/:slug/'
blog = '/blog/:sections[1]/:slug'


[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "index"
  [outputFormats.json]
    mediatype = "application/json"
    baseName = "index"

[params]

		title = "vvvv - visual live-programming for .NET"
		author = "vvvv group"
		description = "vvvv is a visual live-programming environment for .NET"
		
		ogTitle = "vvvv"
		ogDescription = "A visual live-programming environment that takes you from rapid prototyping to final production."

		# The path must be relative to the static folder
		favicon = "favicon.ico"

		# Navigation
		[params.navigation]
		home = "vvvv.org"

		[params.menu]
			[[params.menu.main]]
				name = 'features'
			[[params.menu.main]]
				name = 'blog'
			[[params.menu.main]]
				name = 'showcase'
			[[params.menu.main]]
				name = 'learn'
				url = 'https://thegraybook.vvvv.org/'
			[[params.menu.main]]
				name = 'forum'
				url = 'https://forum.vvvv.org/'
			[[params.menu.main]]
				name = 'community'
			[[params.menu.main]]
				name = 'licensing'
				url = 'https://store.vvvv.org/'
			[[params.menu.main]]
				name = 'support'
			[[params.menu.main]]
				name = 'download'
				style = 'download'


		# Hero section
		[params.Hero]
		vvvv     = "vvvv"
		subtitle   = "<span class='backBox'>A visual live-programming environment that takes you from <b>rapid prototyping</b> to <b>final production.</b></span>"
		tryitButton = "Download"
		tryitButtonLink = "Download"
		requestADemoButton = "Request a tour"
		requestADemoLink = "Support"
		learnmoreButton = "Learn More"
		learnmoreButtonLink = "Features"
		tagsHeadline = "It claims to be popular for:"
		tags = "#creativecoding, #generativedesign, #interactiondesign, #datavisualization, #computervision, #vr, #showcontrol, #physicalcomputing, #datascience, #machinelearning, #dotnet"

		# Overview Section
		[params.Features]
		headline = "Visual Live-Programming with vvvv"

		# Download section
		[params.Download]
		Headline = "Download"
		Copy = 'vvvv is free without any restrictions for non-commercial use.<br/>Commercial use requires a <a href="https://store.vvvv.org/" target="_blank">License</a>.'

		[params.Download.gamma]

		StableLink64 = "https://teamcity.vvvv.org/guestAuth/app/rest/builds/id:39385/artifacts/content/vvvv_gamma_7.0-win-x64_setup.exe"
		StableLinkARM = "https://teamcity.vvvv.org/guestAuth/app/rest/builds/id:39386/artifacts/content/vvvv_gamma_7.0-win-arm64_setup.exe"
		CurrentPreview64BuildType = "vvvv_gamma_Build20225"
		CurrentPreviewArmBuildType = "vvvv_gamma_BuildWinArm64"

		Headline = "vvvv gamma"
		Copy = "First released in April 2020, vvvv gamma is the next generation of vvvv, entirely rewritten from scratch."

		Tab64bit = "Windows"
		TabARM = "Windows Arm"
		TabMac = "Mac / Parallels"

		StableText  = "Download: Stable"
		StableVersion = "Version: 7.0"

		PreviewText = "Download: Preview"
		PreviewLink = "PreviewDownloads"
		PreviewVersion = "Unstable, daily preview builds"

		MacText = '<p>vvvv does not have a native version for macOS!</p><p>But if you`re running on Apple silicon and using <a href="https://www.parallels.com/de/products/desktop/" target="_blank">Parallels</a> is an option for you, please use the "Windows Arm" builds and see <a href="https://thegraybook.vvvv.org/reference/best-practice/vvvv-on-mac.html" target="_blank">Running vvvv on a Mac</a> for some fine-print!</p>'

		LibrariesText  = "Additional Libraries"
		LibrariesLink = "https://thegraybook.vvvv.org/reference/libraries/overview.html"
		LibrariesTarget = "_blank"

		ChangeLogText = "Change Log & Previous Releases"
		ChangeLogLink = "https://thegraybook.vvvv.org/changelog/"
		ChangeLogTarget = "_blank"

		Target = "_self"

		[params.Download.gamma.previewWindow]
		Title = "Latest Previews"
		Subtitle ="Don't use for production!"
		Text = 'These are daily development builds. If you find one to be broken, try an earlier one.<p>Please mark problems you report in the <a href="https://forum.vvvv.org/c/vvvv-gamma/" target="_blank">forum</a> with the *preview* tag or visit us in the <a href="https://app.element.io/#/room/#vvvv:matrix.org" target="_blank">chat</a> to talk about issues you encounter.</p>'

		
		[params.Download.beta]
		Headline = "vvvv beta"
		Copy = "In development since 2001, vvvv beta has been used by many companies worldwide to create large media environments."
		Text  = "Download vvvv beta"
		Link = "https://legacy.vvvv.org/downloads"
		Target = "_blank"

		[params.Showcase]
		headline = "Showcase"
			[params.Showcase.Showreel2]
			title = "Projects 2018 ~ 2024"
			alt = "Works in this reel were realized in the past ~6 years and thus include both vvvv beta as well as pure vvvv gamma projects."
			vimeo = 930568091

			[params.Showcase.Showreel1]
			title = "Projects 2002 ~ 2019"
			alt = "Projects in this showreel were realized mostly with vvvv beta within the past few years."
			vimeo = 371511910

		[params.Blog]
		Title = "Blog"
		NumberOfPosts = 4
		ReadMore = "All posts"
		Warning = "\\* Looking for older blog posts? Find them at: [vvvv.org/blog](https://vvvv.org/blog/1575+1576+25+23+24+39+26+1461+127+126+124)."
		Categories = ["Monthly Reviews", "News", "Development News", "Dates", "vvvv gamma Releases", "vvvv beta Releases", "vvvv beta Addon Releases", "Guest Posts"]
		CommentsDisabled = "Comments are no longer accepted for this post."
		Devvvvs = ["devvvv", "joreg", "gregsn", "tonfilm", "robotanton", "untone", "elias", "azeno", "oschatz", "max"]

	#Community section
	    [params.Community]
	    headline = "Community"

	# Learn section
		[params.Learn]
		headline = "Learn"

	# Support Section
		[params.support]
		headline = "Support"
	# Contact section
		[params.contact]
		headline = "Contact"
		description = " "

		[params.contact.imprint]
		headline = "Imprint"
		text ="vvvv - Dießl & Gregor GbR<br>Oranienstrasse 10 <br> 10997 Berlin/Germany<br>VAT: DE275566955<br><br>groupӘvvvv.org"

		[params.footer]
		hugoText = "Thanks to <a href=\"https://gohugo.io\" target=\"_blank\">Hugo</a> for building this website."
		plausibleText = "Analytics by <a href=\"https://plausible.io\" target=\"_blank\">Plausible</a>."

	# Video blocker
		[params.vimeoBlocker]
		headline="Embedded Vimeo Video"
		text="When playing the video, you accept the [Vimeo privacy policy](https://vimeo.com/privacy)."
		checkbox="Always"
		watchOn="Watch on Vimeo"

		[params.youtubeBlocker]
		headline="Embedded YouTube Video"
		text="When playing the video, you accept the [YouTube privacy policy](https://www.youtube.com/privacy)."
		checkbox="Always"
		watchOn="Watch on YouTube"

